version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  what-is-the-time:
    build: ./whatIsTheTime
    container_name: whatIsTheTime_c
    ports:
      - '5000:5000'
    volumes:
      - ./whatIsTheTime:/app
      - ./app/node_modules
  my-app:
    build: ./my-app
    container_name: myapp_c
    ports:
      - '3000:3000'
    volumes:
      - ./my-app:/app
      - ./app/node_modules
    stdin_open: true
    tty: true



